In [1]:
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
tf.__version__


train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
training_set = train_datagen.flow_from_directory('GNNdataset/Train',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')


test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('GNNdataset/Test',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'categorical')

cnn = tf.keras.models.Sequential()

#Layer 1
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=[64, 64, 3]))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

#Layer 2
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

#Layer 3
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

#Layer 4
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))


cnn.add(tf.keras.layers.Flatten())

cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

cnn.add(tf.keras.layers.Dense(units=3, activation='softmax'))
 
cnn.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

cnn.fit(x = training_set, validation_data = test_set, epochs = 25)


Using TensorFlow backend.


Found 240 images belonging to 3 classes.
Found 60 images belonging to 3 classes.
  ...
    to  
  ['...']
  ...
    to  
  ['...']
Train for 8 steps, validate for 2 steps
Epoch 1/25
8/8 [==============================] - 11s 1s/step - loss: 1.0816 - accuracy: 0.4375 - val_loss: 1.0224 - val_accuracy: 0.3333
Epoch 2/25
8/8 [==============================] - 2s 288ms/step - loss: 0.9744 - accuracy: 0.4583 - val_loss: 0.8045 - val_accuracy: 0.6667
Epoch 3/25
8/8 [==============================] - 2s 276ms/step - loss: 0.7667 - accuracy: 0.6917 - val_loss: 0.4917 - val_accuracy: 0.9500
Epoch 4/25
8/8 [==============================] - 2s 285ms/step - loss: 0.4228 - accuracy: 0.9208 - val_loss: 0.2295 - val_accuracy: 0.9500
Epoch 5/25
8/8 [==============================] - 2s 302ms/step - loss: 0.1702 - accuracy: 0.9792 - val_loss: 0.0638 - val_accuracy: 0.9833
Epoch 6/25
8/8 [==============================] - 2s 275ms/step - loss: 0.0781 - accuracy: 0.9750 - val_loss: 0.0633 - val_accuracy

In [7]:

from PIL import Image
import keras
import base64
from io import BytesIO
import json
import random
import cv2 
import numpy as np
from keras.models import load_model


from keras.preprocessing import image
from tensorflow.keras.models import load_model


face_cascade = cv2.CascadeClassifier('haar_cascade.xml')

def face_extractor(img):

    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face


video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()

    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (64, 64))
        im = Image.fromarray(face, 'RGB')
           
        img_array = np.array(im)
                    
        img_array = np.expand_dims(img_array, axis=0)
        pred = cnn.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][0]>0.5):
            name='Gauri'
            
        if(pred[0][1]>0.5):
            name='Nandini'
            
        if(pred[0][2]>0.5):
            name='Nishita'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()


[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]